### ISSUE TITLE
SYS0002:  The system cannot find the file specified. "KCRYPT10"

### ISSUE THREAD

**Issue by timlank** [komh/kscp#9]
I'm getting this when trying to start KSCP.EXE.  Seems like a pathing issue for OpenSSL?

**Comment by komh** [comment]
I guess. 

If you don't have OpenSSL v1.0.0t, then visit here:

http://bauxite.sakura.ne.jp/software/os2/#openssl

And download **1.0.0t OS2-KNIX runtime**.

**Comment by timlank** [comment]
That OpenSSL (KNIX) works like a charm when extracted into c:\usr\local\bin in ArcaOS v5.0.3.  kscp.exe can be started from 4OS2 shell when executed from the dll directory where KCRYPT10.dll exists and appears in the gui.  There are probably some environment variables that can be set to prevent the need for that.  I have much to learn about ArcaOS.

**Comment by timlank** [comment]
set BEGINLIBPATH=c:\usr\local\bin\dll        
kscp.exe

**Comment by komh** [comment]
Add c:\usr\local\bin\dll to LIBPATH= in CONFIG.SYS, then you can run kscp anywhere without any scripts.
